<#import "parts/common.ftlh" as c>

<@c.page>
    <h5>   This is probably primarily a social network, which already has one hundred million active users. Slightly less than the population in Russia. On the other hand, Swatch is a versatile and collection-friendly photo editor for mobile devices.

        Many people take pictures, feel like creators, capture moments for history, are the most accessible and always like to approach these matters in their mobile phones. But just taking a picture of something is not as interesting as sharing it with friends and acquaintances. You can, of course, put it all on Contact or Facebook, but for this you need to make extra gestures.
    </h5>
</@c.page>